### ISSUE TITLE
version for PostgreSQL 10 and Windows binaries

### ISSUE THREAD

**Issue by zam6ak** [furstenheim/is_jsonb_valid#1]
Hello

Any plans to update this for v10 of PostgreSQL?
Also, any plans to have Windows binaries?

Thanks
Z

**Comment by furstenheim** [comment]
I'm planning to check compatibility for postgres 10 in the next weeks. As for Windows, no. But PR are welcome

**Comment by furstenheim** [comment]
I've checked it and the code is compatible with postgres 10. It should be enough for you to compile the extension in windows
