### ISSUE TITLE
is there a way to throw validation error messages?

### ISSUE THREAD

**Issue by mowses** [furstenheim/is_jsonb_valid#11]
I have downloaded and tested your repo. it is working amazing!
I just have one question: is it possible to throw/return/capture the error messages from the validation?

**Comment by furstenheim** [comment]
Hi mowses,
Great to hear. There's only partial support. If you are compiling from source then you can change at the beginning of the file:

```
define DEBUG_IS_JSONB_VALID false
```

To 
```
define DEBUG_IS_JSONB_VALID true
```
However, this will only log information, the output is the same.

IMHO a validation plugin for the db should sacrifice introspection in favour of speed and consistency. Also getting understandable errors is a very hard problem.

If you want to get better insights at why the validation is failing I recommend to do that at the application level. If you are using node I'd recommend [ajv](https://github.com/ajv-validator/ajv).
