### ISSUE TITLE
Update to never version of JSON Schema specification

### ISSUE THREAD

**Issue by nosovk** [furstenheim/is_jsonb_valid#15]
It would be nice to update to never version of JSON Schema specification. Current version is 2020-12, but at least draft-7 would be enough to get IF statement in schemas.

**Comment by furstenheim** [comment]
Taking a look at this

**Comment by furstenheim** [comment]
I've merged the new function to master.

There were subtle differences with the new draft, and also I preferred to derisk the merge, so I've created a new function  `is_jsonb_valid_draft_v7`, it works as before but it supports draft_v7, in particular the if statements
