### ISSUE TITLE
postgresql-server-dev-NN is required

### ISSUE THREAD

**Issue by karianpour** [furstenheim/is_jsonb_valid#7]
When I run `make install` on ubuntu 16.04 / postgres 11, the system gave me the following error:

```
You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application.
make: *** No rule to make target 'install'.  Stop.
```
Although it was not in the installation process mentioned in read me, I installed :
```
apt install postgresql-server-dev-11
```
I am not sure but I guess that this package is for extension development for Postgres. So, if I want to use this extension in production server, should I install development stuff in production server? Is there a way to just install compiled version of the extension?

**Comment by furstenheim** [comment]
As far as I know, it is possible to compile it in a different server if they are compatible. I'd be glad to accept a PR improving the documentation on this point.
